name: e_commerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  rename: ^2.0.1
  flutter_spinkit: ^5.1.0
  equatable: ^2.0.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.5+3
  http: ^0.13.4
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  http_parser: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
